import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import { ArticleLayout } from "@/components/ArticleLayout";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { siteUrl } from "@/data/authors";

const path = "/panduan/cara-menghitung-7-hari-orang-meninggal/";
const canonical = `${siteUrl}${path}`;
const title = "Cara Menghitung 7 Hari Orang Meninggal (Mitung Dina) | Kalkulator Selamatan";
const description = "Cara menghitung 7 hari kematian dengan metode inklusif dan contoh tanggal nyata. Cek otomatis dengan kalkulator selamatan.";
const image = "/images/cara-menghitung-7-hari-orang-meninggal.webp";

export const metadata: Metadata = { title, description, alternates: { canonical: path }, openGraph: { type: "article", locale: "id_ID", url: path, title, description, images: [{ url: image, width: 1536, height: 1024, alt: "Cara menghitung Mitung Dina dengan kalender dari hari pertama sampai hari ke-7" }] }, twitter: { card: "summary_large_image", title, description, images: [image] } };

const faqs = [
  { question: "Apakah tanggal wafat dihitung sebagai hari pertama?", answer: "Ya. Dalam metode inklusif yang digunakan pada panduan ini, tanggal wafat adalah hari pertama. Karena itu, Mitung Dina atau hari ke-7 didapat dengan menambahkan enam hari kalender." },
  { question: "Jika meninggal pada 14 Februari 2025, kapan 7 harinya?", answer: "Dengan metode inklusif, 7 harinya jatuh pada 20 Februari 2025. Urutannya dimulai dari 14 Februari sebagai hari pertama dan berakhir pada 20 Februari sebagai hari ke-7." },
  { question: "Mengapa hasil hitungan keluarga bisa berbeda?", answer: "Perbedaan dapat muncul karena kebiasaan daerah, penetapan waktu wafat setelah Maghrib, atau cara keluarga memulai hitungan. Gunakan kesepakatan keluarga dan rujukan tokoh setempat bila ada tradisi khusus." },
  { question: "Apakah kalkulator ini bisa dipakai untuk tahapan selamatan lain?", answer: "Bisa. Kalkulator Selamatan menampilkan jadwal 3 hari, 7 hari, 40 hari, 100 hari, Pendhak, dan 1000 hari dari tanggal yang Anda masukkan." },
] as const;

const schema = { "@context": "https://schema.org", "@graph": [
  { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Beranda", item: `${siteUrl}/` }, { "@type": "ListItem", position: 2, name: "Panduan", item: `${siteUrl}/peta-situs/` }, { "@type": "ListItem", position: 3, name: "Cara Menghitung 7 Hari Orang Meninggal", item: canonical }] },
  { "@type": "HowTo", name: "Cara menghitung 7 hari orang meninggal", description: "Hitung Mitung Dina dengan metode inklusif: tanggal wafat sebagai hari pertama, lalu tambah enam hari kalender.", image: `${siteUrl}${image}`, inLanguage: "id-ID", step: [{ "@type": "HowToStep", position: 1, name: "Catat tanggal wafat", text: "Gunakan tanggal wafat sebagai hari pertama dalam hitungan." }, { "@type": "HowToStep", position: 2, name: "Tambahkan enam hari", text: "Untuk mencapai hari ke-7, tambahkan enam hari kalender dari tanggal wafat." }, { "@type": "HowToStep", position: 3, name: "Cocokkan dengan keluarga", text: "Pastikan hasilnya sesuai dengan kesepakatan keluarga atau kebiasaan setempat." }] },
  { "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) },
] };

export default function CaraMenghitungTujuhHariPage() {
  return <><a className="skip-link" href="#main-content">Lewati ke konten utama</a><SiteHeader />
    <main id="main-content" className="article-main"><header className="article-hero"><nav className="article-breadcrumbs" aria-label="Breadcrumb"><Link href="/">Beranda</Link><span aria-hidden="true">/</span><span>Panduan</span></nav><p className="article-kicker">Panduan selamatan Jawa</p><h1>Cara Menghitung 7 Hari Orang Meninggal (Mitung Dina)</h1><p>Untuk menghitung 7 hari orang meninggal dengan metode inklusif, jadikan tanggal wafat sebagai hari pertama lalu tambahkan 6 hari kalender. Cara ini membantu keluarga menentukan tanggal Mitung Dina secara sederhana sebelum mencocokkannya dengan kebiasaan setempat.</p><p className="article-meta">Ditulis oleh <Link href="/penulis/rizky-pratama/">Rizky Pratama</Link> · Diperbarui 27 Juli 2026</p></header>
      <ArticleLayout title={title} description={description} path={path} image={image} datePublished="2026-07-27" dateModified="2026-07-27" className="article-content"><figure className="article-featured-image"><Image src={image} alt="Kalender Mitung Dina yang menunjukkan urutan hari pertama hingga hari ke-7 dan rumus tambah 6 hari" width={1536} height={1024} priority sizes="(max-width: 820px) 100vw, 820px" /><figcaption>Ilustrasi metode inklusif: hari ke-7 dihitung dengan menambahkan 6 hari dari tanggal wafat.</figcaption></figure>
        <div className="article-body"><h2>Apa itu Mitung Dina?</h2><p>Mitung Dina adalah sebutan dalam tradisi Jawa untuk peringatan pada hari ketujuh setelah seseorang meninggal. Dalam urutan selamatan kematian Jawa, tahap ini lazim ditempatkan setelah Geblag dan Nelung Dina, sebelum Matangpuluh, Nyatus, dan Nyewu. Penjelasan mengenai urutan ini dapat ditemukan dalam <a href="https://download.garuda.kemdikbud.go.id/article.php?article=996496&title=MEMAKNAI+KEMATIAN+DALAM+UPACARA+KEMATIAN+DI+JAWA&val=11452" target="_blank" rel="noreferrer">kajian budaya Jawa yang terindeks Garuda</a>.</p><p>Artikel ini memakai metode inklusif karena paling mudah diterapkan pada hitungan tanggal: hari wafat langsung disebut hari pertama. Bila keluarga memiliki pedoman berbeda, misalnya terkait waktu setelah Maghrib atau adat desa, pedoman keluarga tetap menjadi rujukan utama.</p>
          <h2>Rumus hari ke-7: tambah 6 hari</h2><div className="article-callout"><strong>Rumus Mitung Dina:</strong> tanggal wafat + 6 hari kalender = tanggal hari ke-7.</div><ol className="article-step-list"><li><strong>Catat tanggal wafat.</strong> Tanggal tersebut dihitung sebagai hari pertama.</li><li><strong>Tambahkan enam hari kalender.</strong> Jangan menambahkan tujuh hari, karena hari pertama sudah termasuk.</li><li><strong>Cocokkan dengan keluarga.</strong> Pastikan hasil akhirnya selaras dengan kesepakatan dan kebiasaan setempat.</li></ol><p>Jika ingin memeriksa beberapa tahapan sekaligus, gunakan <Link href="/">Kalkulator Selamatan</Link>. Setelah tanggal dimasukkan, alat ini menampilkan jadwal 3 hari, 7 hari, 40 hari, 100 hari, Pendhak, dan 1000 hari.</p>
          <h2>Contoh perhitungan tanggal nyata</h2><p>Misalnya seseorang meninggal pada <strong>14 Februari 2025</strong>. Mulailah hitungan dari tanggal tersebut: 14 Februari adalah hari ke-1, 15 Februari hari ke-2, dan seterusnya. Hari ke-7 jatuh pada <strong>20 Februari 2025</strong>.</p><div className="article-date-grid" aria-label="Contoh urutan hitungan tujuh hari">{["14 Feb · hari 1", "15 Feb · hari 2", "16 Feb · hari 3", "17 Feb · hari 4", "18 Feb · hari 5", "19 Feb · hari 6", "20 Feb · hari 7"].map((item) => <span key={item}>{item}</span>)}</div><p>Contoh ini hanya menunjukkan perhitungan tanggal. Rangkaian acara, waktu pelaksanaan, dan bentuk doa atau selamatan dapat berbeda menurut keluarga dan daerah.</p>
          <h2>Perbedaan metode inklusif dan eksklusif</h2><p>Metode inklusif memasukkan tanggal wafat sebagai hari pertama, sehingga hari ketujuh adalah tambah enam hari. Metode eksklusif baru mulai menghitung pada hari berikutnya dan hasilnya menjadi satu hari lebih lambat. Untuk Mitung Dina, sebaiknya jangan mencampur kedua cara ini dalam satu hitungan.</p><p>Di sejumlah komunitas, pemaknaan selamatan kematian juga dibahas dalam konteks praktik lokal dan kelompok sosial. Sebuah <a href="https://download.garuda.kemdikbud.go.id/article.php?article=2910626&title=Selametan+Day+of+the+Dead+From+a+Javanese+Cultural+Perspective+among+Santri+and+Abangan+a+Case+Study+in+Tulungagung+District&val=25535" target="_blank" rel="noreferrer">studi budaya tentang selametan di Tulungagung</a> menggambarkan adanya konteks praktik yang perlu dihormati ketika memakai panduan tanggal.</p>
          <h2>Kesalahan umum saat menghitung 7 hari</h2><ul><li>Menganggap hari setelah wafat sebagai hari pertama, padahal keluarga memakai metode inklusif.</li><li>Menambahkan tujuh hari penuh, sehingga hasil bergeser satu hari.</li><li>Mengabaikan kesepakatan keluarga mengenai waktu wafat atau kebiasaan setempat.</li><li>Menyalin hasil hitungan tanpa memeriksa kembali tanggal dan tahun yang dimasukkan.</li></ul><p>Untuk penjelasan tentang prinsip situs dan cara kami menyusun panduan, kunjungi halaman <Link href="/tentang-kami/">Tentang Kami</Link> atau profil <Link href="/penulis/rizky-pratama/">Rizky Pratama</Link>.</p>
          <section className="article-faq" aria-labelledby="faq-title"><h2 id="faq-title">Pertanyaan umum</h2>{faqs.map((faq) => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</section><section className="article-references" aria-labelledby="references-title"><h2 id="references-title">Rujukan bacaan</h2><ul><li><a href="https://download.garuda.kemdikbud.go.id/article.php?article=996496&title=MEMAKNAI+KEMATIAN+DALAM+UPACARA+KEMATIAN+DI+JAWA&val=11452" target="_blank" rel="noreferrer">Memaknai Kematian dalam Upacara Kematian di Jawa</a> — portal Garuda.</li><li><a href="https://download.garuda.kemdikbud.go.id/article.php?article=2910626&title=Selametan+Day+of+the+Dead+From+a+Javanese+Cultural+Perspective+among+Santri+and+Abangan+a+Case+Study+in+Tulungagung+District&val=25535" target="_blank" rel="noreferrer">Selametan Day of the Dead from a Javanese Cultural Perspective</a> — portal Garuda.</li></ul></section></div>
      </ArticleLayout></main><SiteFooter /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /></>;
}
